# synthetic_data/constants.py
# Reusable clinical text snippets and common entities for synthetic note generation.

FILLER_TEXT = [
    # Standard clinical phrases
    "The patient's vital signs are stable.",
    "A review of systems was otherwise negative.",
    "He denies any fever, chills, or night sweats.",
    "She denies any nausea, vomiting, or diarrhea.",
    "Past medical history is non-contributory.",
    "The plan was discussed with the patient, who understands and agrees.",
    "Labs from this morning were unremarkable.",
    "Follow-up appointment scheduled in 3 months.",
    "Patient tolerated the procedure well.",
    "No acute distress noted on examination.",
    "Lungs clear to auscultation bilaterally.",
    "Heart: Regular rate and rhythm, no murmurs.",
    "Abdomen: Soft, non-tender, non-distended.",
    "Neurological exam within normal limits.",
    "Patient is afebrile with normal vital signs.",
    "The patient was advised to return if symptoms worsen.",
    "Medications were reconciled during the visit.",
    "Patient reports compliance with current medication regimen.",
    "Imaging studies were reviewed with the patient.",
    "The patient was counseled on lifestyle modifications.",
    # More detailed observations
    "HEENT: Normocephalic, atraumatic. Pupils equal, round, and reactive to light.",
    "Cardiovascular: Regular rate and rhythm. No murmurs, rubs, or gallops. Normal S1 and S2.",
    "Respiratory: Clear to auscultation bilaterally. No wheezes, rales, or rhonchi.",
    "Musculoskeletal: Full range of motion in all extremities. No edema or deformity noted.",
    "Skin: No rashes, lesions, or abnormal pigmentation. Good turgor and hydration.",
    "Psychiatric: Alert and oriented x3. Mood and affect appropriate.",
    "Lymphatic: No cervical, axillary, or inguinal lymphadenopathy.",
    "GI: Bowel sounds present in all four quadrants. No hepatosplenomegaly.",
    # Labs/imaging
    "Complete blood count shows WBC 7.2, Hgb 13.5, Plt 250.",
    "Basic metabolic panel within normal limits with sodium 140, potassium 4.2, creatinine 0.9.",
    "Liver function tests show mild elevation in ALT and AST, likely due to medication effect.",
    "Urinalysis negative for blood, protein, and leukocyte esterase.",
    "CT scan of the head shows no acute intracranial abnormalities.",
    "MRI of the brain demonstrates age-appropriate atrophy without evidence of mass or stroke.",
    "Chest X-ray reveals clear lung fields without infiltrates or effusions.",
    "EKG shows normal sinus rhythm without ST changes or conduction abnormalities.",
    # Plan/follow-up
    "Will continue current medication regimen and reassess in 3 months.",
    "Patient instructed to follow up with specialist for further evaluation.",
    "Recommended lifestyle modifications including diet changes and regular exercise.",
    "Patient given educational materials regarding disease management.",
    "Referral placed for physical therapy twice weekly for 6 weeks.",
    "Will order additional laboratory studies at next visit if symptoms persist.",
    "Patient advised to maintain a symptom diary for review at next appointment.",
]

# Common diagnosis entities (extend or swap per domain)
TOP_DIAGNOSIS_ENTITIES = [
    # Imaging/domain-specific plus general conditions
    "congenital malformation",
    "cerebral hemorrhage",
    "pituitary macroadenoma",
    "disorder of optic nerve",
    "hydrocephalus",
    "disorder of pituitary gland",
    "pituitary adenoma",
    "cyst",
    "pneumocephalus",
    "neoplasm of pituitary gland",
    "disorder of liver",
    "disorder of pancreas",
    "intracranial meningioma",
    "soft tissue lesion",
    "internal carotid artery stenosis",
    "meningitis",
    "radiologic infiltrate of lung",
    # Generic/common
    "hypertension",
    "type 2 diabetes",
    "migraine",
    "asthma",
    "chronic kidney disease",
    "hypothyroidism",
    "hyperlipidemia",
    "osteoarthritis",
    "depression",
    "anxiety disorder",
    "gastroesophageal reflux disease",
    "atrial fibrillation",
    "chronic obstructive pulmonary disease",
    "obesity",
    "coronary artery disease",
    "heart failure",
    "osteoporosis",
    "anemia",
    "vitamin D deficiency",
    "sleep apnea",
]
